# Generated by Django 4.1.6 on 2023-02-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Student Details',
        ),
    ]
