# Generated by Django 4.1.6 on 2023-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=20)),
                ('book_price', models.CharField(max_length=100)),
                ('authors_name', models.CharField(max_length=20)),
                ('author_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
